---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: demo-xfn-creds
spec:
  package: xpkg.upbound.io/jaredorg/demo-xfn-creds:v0.0.7
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.6.0